package main

// DO NOT EDIT: This file was generated by engine. Please regenerate instead of editing or add additional code in a separate file.

import "fmt"
import "reflect"
import "encoding/json"
import "github.com/p9c/sve/engine"
import js "github.com/p9c/sve/pkg/js"

type DemoLine struct {
	Num int `sve:"data"`
}

func (c *DemoLine) Build(vgin *engine.BuildIn) (vgout *engine.BuildOut) {

	vgout = &engine.BuildOut{}

	var vgiterkey interface{}
	_ = vgiterkey
	var vgn *engine.VGNode
	vgn = &sve.VGNode{Type: engine.VGNodeType(3), Data: "li", Attr: []sve.VGAttribute{sve.VGAttribute{Namespace: "", Key: "class", Val: "demo-line"}}}
	vgout.Out = append(vgout.Out, vgn) // root for output
	{
		vgparent := vgn
		_ = vgparent
		vgn = &sve.VGNode{Type: engine.VGNodeType(3), Data: "strong", Attr: []sve.VGAttribute(nil)}
		vgparent.AppendChild(vgn)
		{
			vghtml := fmt.Sprint(c.Num)
			vgn.InnerHTML = &vghtml
		}
		vgn = &sve.VGNode{Type: engine.VGNodeType(1), Data: " a line is here"}
		vgparent.AppendChild(vgn)
	}
	vgn = &sve.VGNode{Type: engine.VGNodeType(3), Data: "style", Attr: []sve.VGAttribute(nil)}
	{
		vgn.AppendChild(&sve.VGNode{Type: engine.VGNodeType(1), Data: "\n.demo-line {\n    color: green;\n}\n", Attr: []sve.VGAttribute(nil)})
	}
	vgout.AppendCSS(vgn)
	return vgout
}

// 'fix' unused imports
var _ fmt.Stringer
var _ reflect.Type
var _ json.RawMessage
var _ js.Value
