package main

// DO NOT EDIT: This file was generated by engine. Please regenerate instead of editing or add additional code in a separate file.

import (
	"fmt"
	"github.com/p9c/sve/engine/component"
)
import "reflect"
import "github.com/p9c/sve/engine"
import js "github.com/p9c/sve/js"

//import "log"

type Root struct {
	Something int
	Success   bool
}

func (c *Root) OnClickRun(event *engine.DOMEvent, n int) {
	c.Success = !c.Success
	//log.Printf("HEY, GOT HERE!")
}
func (c *Root) Build(vgin *component.BuildIn) (vgout *component.BuildOut, vgreterr error) {

	vgout = &component.BuildOut{}

	var vgn *engine.VGNode
	vgn = &engine.VGNode{Type: engine.VGNodeType(3), Data: "span", Attr: []engine.VGAttribute{engine.VGAttribute{Namespace: "", Key: "class", Val: "test-span"}, engine.VGAttribute{Namespace: "", Key: "id", Val: "test_span_id"}}}
	vgout.Out = append(vgout.Out, vgn) // root for output
	{
		vgparent := vgn
		_ = vgparent
		vgn = &engine.VGNode{Type: engine.VGNodeType(1), Data: "\n    This is a test.\n    "}
		vgparent.AppendChild(vgn)
		vgn = &engine.VGNode{Type: engine.VGNodeType(3), Data: "button", Attr: []engine.VGAttribute{engine.VGAttribute{Namespace: "", Key: "id", Val: "run1"}}}
		vgparent.AppendChild(vgn)
		vgn.Attr = append(vgn.Attr, engine.VGAttribute{Key: "data-whatever", Val: fmt.Sprint(c.Something)})
		vgn.DOMEventHandlerSpecList = append(vgn.DOMEventHandlerSpecList, engine.DOMEventHandlerSpec{
			EventType: "click",
			Func:      func(event *engine.DOMEvent) { c.OnClickRun(event, 7) },
			// TODO: implement capture, etc. mostly need to decide syntax
		})
		{
			vgparent := vgn
			_ = vgparent
			vgn = &engine.VGNode{Type: engine.VGNodeType(1), Data: "run1"}
			vgparent.AppendChild(vgn)
		}
		vgn = &engine.VGNode{Type: engine.VGNodeType(1), Data: "\n    "}
		vgparent.AppendChild(vgn)
		vgn = &engine.VGNode{Type: engine.VGNodeType(3), Data: "button", Attr: []engine.VGAttribute{engine.VGAttribute{Namespace: "", Key: "id", Val: "run2"}}}
		vgparent.AppendChild(vgn)
		vgn.Attr = append(vgn.Attr, engine.VGAttribute{Key: "data-whatever", Val: fmt.Sprint(c.Something)})
		vgn.DOMEventHandlerSpecList = append(vgn.DOMEventHandlerSpecList, engine.DOMEventHandlerSpec{
			EventType: "click",
			Func:      func(event *engine.DOMEvent) { c.Success = !c.Success },
			// TODO: implement capture, etc. mostly need to decide syntax
		})
		{
			vgparent := vgn
			_ = vgparent
			vgn = &engine.VGNode{Type: engine.VGNodeType(1), Data: "run2"}
			vgparent.AppendChild(vgn)
		}
		vgn = &engine.VGNode{Type: engine.VGNodeType(1), Data: "\n    "}
		vgparent.AppendChild(vgn)
		if c.Success {
			vgn = &engine.VGNode{Type: engine.VGNodeType(3), Data: "div", Attr: []engine.VGAttribute{engine.VGAttribute{Namespace: "", Key: "id", Val: "success"}}}
			vgparent.AppendChild(vgn)
			{
				vgparent := vgn
				_ = vgparent
				vgn = &engine.VGNode{Type: engine.VGNodeType(1), Data: "success"}
				vgparent.AppendChild(vgn)
			}
		}
		vgn = &engine.VGNode{Type: engine.VGNodeType(1), Data: "\n    "}
		vgparent.AppendChild(vgn)
		vgn = &engine.VGNode{Type: engine.VGNodeType(3), Data: "div", Attr: []engine.VGAttribute(nil)}
		vgparent.AppendChild(vgn)
		{
			vghtml := "Some <strong>content</strong> here"
			vgn.InnerHTML = &vghtml
		}
		vgn = &engine.VGNode{Type: engine.VGNodeType(1), Data: "\n"}
		vgparent.AppendChild(vgn)
	}
	return vgout, nil
}

// 'fix' unused imports
var _ = fmt.Sprintf
var _ = reflect.New
var _ = js.ValueOf
