// +build minimal

#pragma once

#ifndef GO_QTWEBENGINE_H
#define GO_QTWEBENGINE_H

#include <stdint.h>

#ifdef __cplusplus
int QWebEnginePage_QWebEnginePage_QRegisterMetaType();
int QWebEngineProfile_QWebEngineProfile_QRegisterMetaType();
int QWebEngineView_QWebEngineView_QRegisterMetaType();
extern "C" {
#endif

struct QtWebEngine_PackedString { char* data; long long len; };
struct QtWebEngine_PackedList { void* data; long long len; };
void* QWebEngineHttpRequest_NewQWebEngineHttpRequest(void* url, long long method);
void* QWebEngineHttpRequest_NewQWebEngineHttpRequest2(void* other);
void* QWebEngineHttpRequest_Header(void* ptr, void* headerName);
struct QtWebEngine_PackedList QWebEngineHttpRequest_Headers(void* ptr);
long long QWebEngineHttpRequest_Method(void* ptr);
void QWebEngineHttpRequest_SetHeader(void* ptr, void* headerName, void* headerValue);
void QWebEngineHttpRequest_SetUrl(void* ptr, void* url);
void QWebEngineHttpRequest_Swap(void* ptr, void* other);
void* QWebEngineHttpRequest_Url(void* ptr);
void QWebEngineHttpRequest_DestroyQWebEngineHttpRequest(void* ptr);
void* QWebEngineHttpRequest___headers_atList(void* ptr, int i);
void QWebEngineHttpRequest___headers_setList(void* ptr, void* i);
void* QWebEngineHttpRequest___headers_newList(void* ptr);
struct QtWebEngine_PackedString QWebEngineHttpRequest___postRequest_postData_atList(void* ptr, struct QtWebEngine_PackedString v, int i);
void QWebEngineHttpRequest___postRequest_postData_setList(void* ptr, struct QtWebEngine_PackedString key, struct QtWebEngine_PackedString i);
void* QWebEngineHttpRequest___postRequest_postData_newList(void* ptr);
struct QtWebEngine_PackedList QWebEngineHttpRequest___postRequest_postData_keyList(void* ptr);
struct QtWebEngine_PackedString QWebEngineHttpRequest_____postRequest_postData_keyList_atList(void* ptr, int i);
void QWebEngineHttpRequest_____postRequest_postData_keyList_setList(void* ptr, struct QtWebEngine_PackedString i);
void* QWebEngineHttpRequest_____postRequest_postData_keyList_newList(void* ptr);
void* QWebEnginePage_NewQWebEnginePage(void* parent);
void* QWebEnginePage_NewQWebEnginePage2(void* profile, void* parent);
void* QWebEnginePage_Action(void* ptr, long long action);
void* QWebEnginePage_BackgroundColor(void* ptr);
void* QWebEnginePage_CreateStandardContextMenu(void* ptr);
void* QWebEnginePage_CreateWindow(void* ptr, long long ty);
void* QWebEnginePage_CreateWindowDefault(void* ptr, long long ty);
void QWebEnginePage_Download(void* ptr, void* url, struct QtWebEngine_PackedString filename);
char QWebEnginePage_EventDefault(void* ptr, void* vqe);
char QWebEnginePage_HasSelection(void* ptr);
void* QWebEnginePage_Icon(void* ptr);
void QWebEnginePage_ConnectIconChanged(void* ptr, long long t);
void QWebEnginePage_DisconnectIconChanged(void* ptr);
void QWebEnginePage_IconChanged(void* ptr, void* icon);
void QWebEnginePage_ConnectLinkHovered(void* ptr, long long t);
void QWebEnginePage_DisconnectLinkHovered(void* ptr);
void QWebEnginePage_LinkHovered(void* ptr, struct QtWebEngine_PackedString url);
void QWebEnginePage_Load(void* ptr, void* url);
void QWebEnginePage_Load2(void* ptr, void* request);
void* QWebEnginePage_MetaObjectDefault(void* ptr);
void QWebEnginePage_Print(void* ptr, void* printer);
void* QWebEnginePage_Profile(void* ptr);
void QWebEnginePage_RunJavaScript(void* ptr, struct QtWebEngine_PackedString scriptSource);
void QWebEnginePage_RunJavaScript2(void* ptr, struct QtWebEngine_PackedString scriptSource, unsigned int worldId);
struct QtWebEngine_PackedString QWebEnginePage_SelectedText(void* ptr);
void QWebEnginePage_ConnectSelectionChanged(void* ptr, long long t);
void QWebEnginePage_DisconnectSelectionChanged(void* ptr);
void QWebEnginePage_SelectionChanged(void* ptr);
void QWebEnginePage_SetBackgroundColor(void* ptr, void* color);
void QWebEnginePage_SetContent(void* ptr, void* data, struct QtWebEngine_PackedString mimeType, void* baseUrl);
void QWebEnginePage_SetHtml(void* ptr, struct QtWebEngine_PackedString html, void* baseUrl);
void QWebEnginePage_SetUrl(void* ptr, void* url);
void QWebEnginePage_SetView(void* ptr, void* view);
void* QWebEnginePage_Settings(void* ptr);
struct QtWebEngine_PackedString QWebEnginePage_Title(void* ptr);
void QWebEnginePage_ConnectTitleChanged(void* ptr, long long t);
void QWebEnginePage_DisconnectTitleChanged(void* ptr);
void QWebEnginePage_TitleChanged(void* ptr, struct QtWebEngine_PackedString title);
struct QtWebEngine_PackedString QWebEnginePage_QWebEnginePage_Tr(char* s, char* c, int n);
void QWebEnginePage_TriggerAction(void* ptr, long long action, char checked);
void QWebEnginePage_TriggerActionDefault(void* ptr, long long action, char checked);
void* QWebEnginePage_Url(void* ptr);
void QWebEnginePage_ConnectUrlChanged(void* ptr, long long t);
void QWebEnginePage_DisconnectUrlChanged(void* ptr);
void QWebEnginePage_UrlChanged(void* ptr, void* url);
void* QWebEnginePage_View(void* ptr);
void QWebEnginePage_DestroyQWebEnginePage(void* ptr);
void QWebEnginePage_DestroyQWebEnginePageDefault(void* ptr);
void* QWebEnginePage___dynamicPropertyNames_atList(void* ptr, int i);
void QWebEnginePage___dynamicPropertyNames_setList(void* ptr, void* i);
void* QWebEnginePage___dynamicPropertyNames_newList(void* ptr);
void* QWebEnginePage___findChildren_atList2(void* ptr, int i);
void QWebEnginePage___findChildren_setList2(void* ptr, void* i);
void* QWebEnginePage___findChildren_newList2(void* ptr);
void* QWebEnginePage___findChildren_atList3(void* ptr, int i);
void QWebEnginePage___findChildren_setList3(void* ptr, void* i);
void* QWebEnginePage___findChildren_newList3(void* ptr);
void* QWebEnginePage___findChildren_atList(void* ptr, int i);
void QWebEnginePage___findChildren_setList(void* ptr, void* i);
void* QWebEnginePage___findChildren_newList(void* ptr);
void* QWebEnginePage___children_atList(void* ptr, int i);
void QWebEnginePage___children_setList(void* ptr, void* i);
void* QWebEnginePage___children_newList(void* ptr);
char QWebEnginePage_EventFilterDefault(void* ptr, void* watched, void* event);
void QWebEnginePage_ChildEventDefault(void* ptr, void* event);
void QWebEnginePage_ConnectNotifyDefault(void* ptr, void* sign);
void QWebEnginePage_CustomEventDefault(void* ptr, void* event);
void QWebEnginePage_DeleteLaterDefault(void* ptr);
void QWebEnginePage_DisconnectNotifyDefault(void* ptr, void* sign);
void QWebEnginePage_TimerEventDefault(void* ptr, void* event);
void* QWebEngineProfile_NewQWebEngineProfile(void* parent);
void* QWebEngineProfile_NewQWebEngineProfile2(struct QtWebEngine_PackedString name, void* parent);
void* QWebEngineProfile_MetaObjectDefault(void* ptr);
void* QWebEngineProfile_Settings(void* ptr);
struct QtWebEngine_PackedString QWebEngineProfile_QWebEngineProfile_Tr(char* s, char* c, int n);
void QWebEngineProfile_DestroyQWebEngineProfile(void* ptr);
void QWebEngineProfile_DestroyQWebEngineProfileDefault(void* ptr);
void* QWebEngineProfile___clearVisitedLinks_urls_atList(void* ptr, int i);
void QWebEngineProfile___clearVisitedLinks_urls_setList(void* ptr, void* i);
void* QWebEngineProfile___clearVisitedLinks_urls_newList(void* ptr);
void* QWebEngineProfile___dynamicPropertyNames_atList(void* ptr, int i);
void QWebEngineProfile___dynamicPropertyNames_setList(void* ptr, void* i);
void* QWebEngineProfile___dynamicPropertyNames_newList(void* ptr);
void* QWebEngineProfile___findChildren_atList2(void* ptr, int i);
void QWebEngineProfile___findChildren_setList2(void* ptr, void* i);
void* QWebEngineProfile___findChildren_newList2(void* ptr);
void* QWebEngineProfile___findChildren_atList3(void* ptr, int i);
void QWebEngineProfile___findChildren_setList3(void* ptr, void* i);
void* QWebEngineProfile___findChildren_newList3(void* ptr);
void* QWebEngineProfile___findChildren_atList(void* ptr, int i);
void QWebEngineProfile___findChildren_setList(void* ptr, void* i);
void* QWebEngineProfile___findChildren_newList(void* ptr);
void* QWebEngineProfile___children_atList(void* ptr, int i);
void QWebEngineProfile___children_setList(void* ptr, void* i);
void* QWebEngineProfile___children_newList(void* ptr);
char QWebEngineProfile_EventDefault(void* ptr, void* e);
char QWebEngineProfile_EventFilterDefault(void* ptr, void* watched, void* event);
void QWebEngineProfile_ChildEventDefault(void* ptr, void* event);
void QWebEngineProfile_ConnectNotifyDefault(void* ptr, void* sign);
void QWebEngineProfile_CustomEventDefault(void* ptr, void* event);
void QWebEngineProfile_DeleteLaterDefault(void* ptr);
void QWebEngineProfile_DisconnectNotifyDefault(void* ptr, void* sign);
void QWebEngineProfile_TimerEventDefault(void* ptr, void* event);
void* QWebEngineSettings_NewQWebEngineSettings2(void* parentSettings);
struct QtWebEngine_PackedString QWebEngineSettings_FontFamily(void* ptr, long long which);
int QWebEngineSettings_FontSize(void* ptr, long long ty);
void QWebEngineSettings_SetAttribute(void* ptr, long long attr, char on);
void QWebEngineSettings_SetFontFamily(void* ptr, long long which, struct QtWebEngine_PackedString family);
char QWebEngineSettings_TestAttribute(void* ptr, long long attr);
void QWebEngineSettings_DestroyQWebEngineSettings(void* ptr);
void* QWebEngineView_NewQWebEngineView(void* parent);
void QWebEngineView_Back(void* ptr);
void QWebEngineView_BackDefault(void* ptr);
void QWebEngineView_ContextMenuEventDefault(void* ptr, void* vqc);
void QWebEngineView_DragEnterEventDefault(void* ptr, void* e);
void QWebEngineView_DragLeaveEventDefault(void* ptr, void* e);
void QWebEngineView_DragMoveEventDefault(void* ptr, void* e);
void QWebEngineView_DropEventDefault(void* ptr, void* e);
char QWebEngineView_EventDefault(void* ptr, void* vqe);
void QWebEngineView_Forward(void* ptr);
void QWebEngineView_ForwardDefault(void* ptr);
char QWebEngineView_HasSelection(void* ptr);
void QWebEngineView_HideEventDefault(void* ptr, void* vqh);
void* QWebEngineView_Icon(void* ptr);
void QWebEngineView_ConnectIconChanged(void* ptr, long long t);
void QWebEngineView_DisconnectIconChanged(void* ptr);
void QWebEngineView_IconChanged(void* ptr, void* vqi);
void QWebEngineView_Load(void* ptr, void* url);
void QWebEngineView_Load2(void* ptr, void* request);
void* QWebEngineView_MetaObjectDefault(void* ptr);
void* QWebEngineView_Page(void* ptr);
void QWebEngineView_Reload(void* ptr);
void QWebEngineView_ReloadDefault(void* ptr);
struct QtWebEngine_PackedString QWebEngineView_SelectedText(void* ptr);
void QWebEngineView_ConnectSelectionChanged(void* ptr, long long t);
void QWebEngineView_DisconnectSelectionChanged(void* ptr);
void QWebEngineView_SelectionChanged(void* ptr);
void QWebEngineView_SetContent(void* ptr, void* data, struct QtWebEngine_PackedString mimeType, void* baseUrl);
void QWebEngineView_SetHtml(void* ptr, struct QtWebEngine_PackedString html, void* baseUrl);
void QWebEngineView_SetPage(void* ptr, void* page);
void QWebEngineView_SetUrl(void* ptr, void* url);
void* QWebEngineView_Settings(void* ptr);
void QWebEngineView_ShowEventDefault(void* ptr, void* vqs);
void* QWebEngineView_SizeHintDefault(void* ptr);
void QWebEngineView_Stop(void* ptr);
void QWebEngineView_StopDefault(void* ptr);
struct QtWebEngine_PackedString QWebEngineView_Title(void* ptr);
void QWebEngineView_ConnectTitleChanged(void* ptr, long long t);
void QWebEngineView_DisconnectTitleChanged(void* ptr);
void QWebEngineView_TitleChanged(void* ptr, struct QtWebEngine_PackedString title);
struct QtWebEngine_PackedString QWebEngineView_QWebEngineView_Tr(char* s, char* c, int n);
void* QWebEngineView_Url(void* ptr);
void QWebEngineView_ConnectUrlChanged(void* ptr, long long t);
void QWebEngineView_DisconnectUrlChanged(void* ptr);
void QWebEngineView_UrlChanged(void* ptr, void* vqu);
void QWebEngineView_DestroyQWebEngineView(void* ptr);
void QWebEngineView_DestroyQWebEngineViewDefault(void* ptr);
void* QWebEngineView___addActions_actions_atList(void* ptr, int i);
void QWebEngineView___addActions_actions_setList(void* ptr, void* i);
void* QWebEngineView___addActions_actions_newList(void* ptr);
void* QWebEngineView___insertActions_actions_atList(void* ptr, int i);
void QWebEngineView___insertActions_actions_setList(void* ptr, void* i);
void* QWebEngineView___insertActions_actions_newList(void* ptr);
void* QWebEngineView___actions_atList(void* ptr, int i);
void QWebEngineView___actions_setList(void* ptr, void* i);
void* QWebEngineView___actions_newList(void* ptr);
void* QWebEngineView___dynamicPropertyNames_atList(void* ptr, int i);
void QWebEngineView___dynamicPropertyNames_setList(void* ptr, void* i);
void* QWebEngineView___dynamicPropertyNames_newList(void* ptr);
void* QWebEngineView___findChildren_atList2(void* ptr, int i);
void QWebEngineView___findChildren_setList2(void* ptr, void* i);
void* QWebEngineView___findChildren_newList2(void* ptr);
void* QWebEngineView___findChildren_atList3(void* ptr, int i);
void QWebEngineView___findChildren_setList3(void* ptr, void* i);
void* QWebEngineView___findChildren_newList3(void* ptr);
void* QWebEngineView___findChildren_atList(void* ptr, int i);
void QWebEngineView___findChildren_setList(void* ptr, void* i);
void* QWebEngineView___findChildren_newList(void* ptr);
void* QWebEngineView___children_atList(void* ptr, int i);
void QWebEngineView___children_setList(void* ptr, void* i);
void* QWebEngineView___children_newList(void* ptr);
char QWebEngineView_CloseDefault(void* ptr);
char QWebEngineView_FocusNextPrevChildDefault(void* ptr, char next);
char QWebEngineView_NativeEventDefault(void* ptr, void* eventType, void* message, long* result);
void QWebEngineView_ActionEventDefault(void* ptr, void* event);
void QWebEngineView_ChangeEventDefault(void* ptr, void* event);
void QWebEngineView_CloseEventDefault(void* ptr, void* event);
void QWebEngineView_EnterEventDefault(void* ptr, void* event);
void QWebEngineView_FocusInEventDefault(void* ptr, void* event);
void QWebEngineView_FocusOutEventDefault(void* ptr, void* event);
void QWebEngineView_HideDefault(void* ptr);
void QWebEngineView_InputMethodEventDefault(void* ptr, void* event);
void QWebEngineView_KeyPressEventDefault(void* ptr, void* event);
void QWebEngineView_KeyReleaseEventDefault(void* ptr, void* event);
void QWebEngineView_LeaveEventDefault(void* ptr, void* event);
void QWebEngineView_LowerDefault(void* ptr);
void QWebEngineView_MouseDoubleClickEventDefault(void* ptr, void* event);
void QWebEngineView_MouseMoveEventDefault(void* ptr, void* event);
void QWebEngineView_MousePressEventDefault(void* ptr, void* event);
void QWebEngineView_MouseReleaseEventDefault(void* ptr, void* event);
void QWebEngineView_MoveEventDefault(void* ptr, void* event);
void QWebEngineView_PaintEventDefault(void* ptr, void* event);
void QWebEngineView_RaiseDefault(void* ptr);
void QWebEngineView_RepaintDefault(void* ptr);
void QWebEngineView_ResizeEventDefault(void* ptr, void* event);
void QWebEngineView_SetDisabledDefault(void* ptr, char disable);
void QWebEngineView_SetEnabledDefault(void* ptr, char vbo);
void QWebEngineView_SetFocus2Default(void* ptr);
void QWebEngineView_SetHiddenDefault(void* ptr, char hidden);
void QWebEngineView_SetStyleSheetDefault(void* ptr, struct QtWebEngine_PackedString styleSheet);
void QWebEngineView_SetVisibleDefault(void* ptr, char visible);
void QWebEngineView_SetWindowModifiedDefault(void* ptr, char vbo);
void QWebEngineView_SetWindowTitleDefault(void* ptr, struct QtWebEngine_PackedString vqs);
void QWebEngineView_ShowDefault(void* ptr);
void QWebEngineView_ShowFullScreenDefault(void* ptr);
void QWebEngineView_ShowMaximizedDefault(void* ptr);
void QWebEngineView_ShowMinimizedDefault(void* ptr);
void QWebEngineView_ShowNormalDefault(void* ptr);
void QWebEngineView_TabletEventDefault(void* ptr, void* event);
void QWebEngineView_UpdateDefault(void* ptr);
void QWebEngineView_UpdateMicroFocusDefault(void* ptr);
void QWebEngineView_WheelEventDefault(void* ptr, void* event);
void* QWebEngineView_PaintEngineDefault(void* ptr);
void* QWebEngineView_MinimumSizeHintDefault(void* ptr);
void* QWebEngineView_InputMethodQueryDefault(void* ptr, long long query);
char QWebEngineView_HasHeightForWidthDefault(void* ptr);
int QWebEngineView_HeightForWidthDefault(void* ptr, int w);
int QWebEngineView_MetricDefault(void* ptr, long long m);
void QWebEngineView_InitPainterDefault(void* ptr, void* painter);
char QWebEngineView_EventFilterDefault(void* ptr, void* watched, void* event);
void QWebEngineView_ChildEventDefault(void* ptr, void* event);
void QWebEngineView_ConnectNotifyDefault(void* ptr, void* sign);
void QWebEngineView_CustomEventDefault(void* ptr, void* event);
void QWebEngineView_DeleteLaterDefault(void* ptr);
void QWebEngineView_DisconnectNotifyDefault(void* ptr, void* sign);
void QWebEngineView_TimerEventDefault(void* ptr, void* event);

#ifdef __cplusplus
}
#endif

#endif